import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://koovlo.com'

  const tools = [
    '/tools/pdf/merge',
    '/tools/pdf/split',
    '/tools/pdf/compress',
    '/tools/pdf/rotate',
    '/tools/pdf/reorder',
    '/tools/pdf/to-image',
    '/tools/pdf/to-pdf',
    '/tools/pdf/watermark',
    '/tools/pdf/unlock',
    '/tools/pdf/to-word',
    '/tools/pdf/page-number',
    '/tools/pdf/grayscale',
    '/tools/pdf/metadata',
    '/tools/pdf/analyzer',
    '/tools/pdf/sign',
    '/tools/image/resize',
    '/tools/image/compress',
    '/tools/image/crop',
    '/tools/image/rotate',
    '/tools/image/flip',
    '/tools/image/convert',
    '/tools/image/quality',
    '/tools/image/webp',
    '/tools/image/blur',
    '/tools/image/grayscale',
    '/tools/image/brightness',
    '/tools/image/saturation',
    '/tools/image/sepia',
    '/tools/image/invert',
    '/tools/image/add-text',
    '/tools/image/add-watermark',
    '/tools/image/annotate',
    '/tools/image/border',
    '/tools/image/to-base64',
    '/tools/image/from-base64',
    '/tools/image/dimensions',
    '/tools/image/bulk-resize',
    '/tools/image/bulk-convert',
    '/tools/image/bulk-compress',
    '/tools/image/bg-remove',
    '/tools/education/percentage',
    '/tools/education/cgpa',
    '/tools/education/gpa',
    '/tools/education/marks-percentage',
    '/tools/education/grade',
    '/tools/education/attendance',
    '/tools/education/rank',
    '/tools/education/word-counter',
    '/tools/education/reading-time',
    '/tools/education/text-summarizer',
    '/tools/education/flashcard',
    '/tools/education/quiz-generator',
    '/tools/education/notes-organizer',
    '/tools/education/scientific-calc',
    '/tools/education/unit-converter',
    '/tools/education/fraction-calc',
    '/tools/education/average',
    '/tools/education/speed-distance-time',
    '/tools/education/interest',
    '/tools/education/timer',
    '/tools/education/answer-sheet',
    '/tools/education/omr-sheet',
    '/tools/education/revision-planner',
    '/tools/education/checklist',
    '/tools/document/resume-builder',
    '/tools/document/cv-builder',
    '/tools/document/invoice',
    '/tools/document/bill',
    '/tools/document/quotation',
    '/tools/document/business-card',
    '/tools/document/letterhead',
    '/tools/document/certificate',
    '/tools/document/id-card',
    '/tools/document/experience-letter',
    '/tools/document/offer-letter',
    '/tools/document/bonafide',
    '/tools/document/salary-slip',
    '/tools/document/report-cover',
    '/tools/text-web/word-counter',
    '/tools/text-web/char-counter',
    '/tools/text-web/case-converter',
    '/tools/text-web/remove-spaces',
    '/tools/text-web/text-sorter',
    '/tools/text-web/text-replacer',
    '/tools/text-web/text-to-speech',
    '/tools/text-web/speech-to-text',
    '/tools/text-web/json-formatter',
    '/tools/text-web/json-validator',
    '/tools/text-web/base64',
    '/tools/text-web/url-encode',
    '/tools/text-web/html-minifier',
    '/tools/text-web/css-minifier',
    '/tools/text-web/js-minifier',
    '/tools/text-web/regex-tester',
    '/tools/text-web/lorem-ipsum',
    '/tools/text-web/meta-generator',
    '/tools/file/zip-creator',
    '/tools/file/size-checker',
    '/tools/file/bulk-renamer',
    '/tools/file/text-to-pdf',
    '/tools/file/pdf-to-text',
  ]

  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${baseUrl}/tools`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    ...tools.map(tool => ({
      url: `${baseUrl}${tool}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
  ]
}